# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/rdave009/final-project-rdave009-xlai015-hliu246-aneva018

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/rdave009/final-project-rdave009-xlai015-hliu246-aneva018

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/rdave009/final-project-rdave009-xlai015-hliu246-aneva018/CMakeFiles /home/csmajs/rdave009/final-project-rdave009-xlai015-hliu246-aneva018//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/rdave009/final-project-rdave009-xlai015-hliu246-aneva018/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runMain

# Build rule for target.
runMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runMain
.PHONY : runMain

# fast build rule for target.
runMain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/build
.PHONY : runMain/fast

AdminUser.o: AdminUser.cpp.o
.PHONY : AdminUser.o

# target to build an object file
AdminUser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/AdminUser.cpp.o
.PHONY : AdminUser.cpp.o

AdminUser.i: AdminUser.cpp.i
.PHONY : AdminUser.i

# target to preprocess a source file
AdminUser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/AdminUser.cpp.i
.PHONY : AdminUser.cpp.i

AdminUser.s: AdminUser.cpp.s
.PHONY : AdminUser.s

# target to generate assembly for a file
AdminUser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/AdminUser.cpp.s
.PHONY : AdminUser.cpp.s

UserDatabase.o: UserDatabase.cpp.o
.PHONY : UserDatabase.o

# target to build an object file
UserDatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/UserDatabase.cpp.o
.PHONY : UserDatabase.cpp.o

UserDatabase.i: UserDatabase.cpp.i
.PHONY : UserDatabase.i

# target to preprocess a source file
UserDatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/UserDatabase.cpp.i
.PHONY : UserDatabase.cpp.i

UserDatabase.s: UserDatabase.cpp.s
.PHONY : UserDatabase.s

# target to generate assembly for a file
UserDatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/UserDatabase.cpp.s
.PHONY : UserDatabase.cpp.s

book.o: book.cpp.o
.PHONY : book.o

# target to build an object file
book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/book.cpp.o
.PHONY : book.cpp.o

book.i: book.cpp.i
.PHONY : book.i

# target to preprocess a source file
book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/book.cpp.i
.PHONY : book.cpp.i

book.s: book.cpp.s
.PHONY : book.s

# target to generate assembly for a file
book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/book.cpp.s
.PHONY : book.cpp.s

display.o: display.cpp.o
.PHONY : display.o

# target to build an object file
display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/display.cpp.o
.PHONY : display.cpp.o

display.i: display.cpp.i
.PHONY : display.i

# target to preprocess a source file
display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/display.cpp.i
.PHONY : display.cpp.i

display.s: display.cpp.s
.PHONY : display.s

# target to generate assembly for a file
display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/display.cpp.s
.PHONY : display.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/main.cpp.s
.PHONY : main.cpp.s

user.o: user.cpp.o
.PHONY : user.o

# target to build an object file
user.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/user.cpp.o
.PHONY : user.cpp.o

user.i: user.cpp.i
.PHONY : user.i

# target to preprocess a source file
user.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/user.cpp.i
.PHONY : user.cpp.i

user.s: user.cpp.s
.PHONY : user.s

# target to generate assembly for a file
user.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/user.cpp.s
.PHONY : user.cpp.s

userDisplay.o: userDisplay.cpp.o
.PHONY : userDisplay.o

# target to build an object file
userDisplay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/userDisplay.cpp.o
.PHONY : userDisplay.cpp.o

userDisplay.i: userDisplay.cpp.i
.PHONY : userDisplay.i

# target to preprocess a source file
userDisplay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/userDisplay.cpp.i
.PHONY : userDisplay.cpp.i

userDisplay.s: userDisplay.cpp.s
.PHONY : userDisplay.s

# target to generate assembly for a file
userDisplay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runMain.dir/build.make CMakeFiles/runMain.dir/userDisplay.cpp.s
.PHONY : userDisplay.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... runMain"
	@echo "... AdminUser.o"
	@echo "... AdminUser.i"
	@echo "... AdminUser.s"
	@echo "... UserDatabase.o"
	@echo "... UserDatabase.i"
	@echo "... UserDatabase.s"
	@echo "... book.o"
	@echo "... book.i"
	@echo "... book.s"
	@echo "... display.o"
	@echo "... display.i"
	@echo "... display.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... user.o"
	@echo "... user.i"
	@echo "... user.s"
	@echo "... userDisplay.o"
	@echo "... userDisplay.i"
	@echo "... userDisplay.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

